#!/usr/bin/env perl

# If we list all the natural numbers below 10 that are multiples 
# of 3 or 5, we get 3, 5, 6 and 9. The sum of these multiples is 
# 23.
#
# Find the sum of all the multiples of 3 or 5 below 1000.

use   strict;
use warnings;
use feature qw( say );

sub find {
    my $sum = 0;
    for(0..1000) {
        next if 0 != ($_ % 3) or 0 != ($_ % 5);
        $sum += $_
    }
    return $sum
}

say &find
